/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */import javax.swing.ButtonGroup;

/**
 *
 * @author nilei4218
 */
public class LOLTQ extends javax.swing.JFrame {
        int point = 0;
    /**
     * Creates new form LOLTQ
     */
    public LOLTQ() {
        initComponents();
        groupButton();
        //keep the questions invisible for starting screen
        q1.setVisible(false);
        q2.setVisible(false);
        q3.setVisible(false);
        q4.setVisible(false);
        
        //set buttons invisible untill user reaches it's page
        b.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        
//        Why.setVisible(false);
//        story.setVisible(false);
    }
    private void groupButton(){
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(q1);
        bg1.add(q2);
        bg1.add(q3);
        bg1.add(q4);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WUR = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        q1 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JRadioButton();
        q3 = new javax.swing.JRadioButton();
        q4 = new javax.swing.JRadioButton();
        pic1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        WUR.setFont(new java.awt.Font("PosterBodoni Win95BT", 0, 14)); // NOI18N
        WUR.setForeground(new java.awt.Color(204, 204, 0));
        WUR.setText("                                       What Toxic Champion Are You?");

        b1.setBackground(new java.awt.Color(204, 204, 204));
        b1.setText("Start");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        q1.setBackground(new java.awt.Color(0, 0, 204));
        q1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        q1.setForeground(new java.awt.Color(255, 255, 255));
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        q2.setBackground(new java.awt.Color(0, 0, 204));
        q2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        q2.setForeground(new java.awt.Color(255, 255, 255));
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });

        q3.setBackground(new java.awt.Color(0, 0, 204));
        q3.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        q3.setForeground(new java.awt.Color(255, 255, 255));
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });

        q4.setBackground(new java.awt.Color(0, 0, 204));
        q4.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        q4.setForeground(new java.awt.Color(255, 255, 255));
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N

        b2.setText("Next");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b6.setText("End");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setText("Next");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setText("Next");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b3.setText("Next");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b.setText("Next");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3)
                            .addComponent(q1)
                            .addComponent(q2)
                            .addComponent(q4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(pic1)
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2)
                        .addGap(2, 2, 2)
                        .addComponent(b3)
                        .addGap(2, 2, 2)
                        .addComponent(b4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(WUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(WUR)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q1)
                        .addGap(26, 26, 26)
                        .addComponent(q2)
                        .addGap(42, 42, 42)
                        .addComponent(q3)
                        .addGap(28, 28, 28)
                        .addComponent(q4)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6)
                    .addComponent(b)
                    .addComponent(b2))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        //new LearnStuff().setVisible(true);
        //make the questions visible for user to see
        q1.setVisible(true);
        q2.setVisible(true);
        q3.setVisible(true);
        q4.setVisible(true);
        b.setVisible(true);
        b1.setVisible(false);
        pic1.setVisible(false);
    }//GEN-LAST:event_b1ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
       
    }//GEN-LAST:event_q1ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        //gets rid of 1st button and add second
        b2.setVisible(false);
        b3.setVisible(true);
        
        WUR.setText("If you over hear someone saying bad thing about you, what would you do");
        q1.setText("Say jesus loves you");
        q2.setText("Bring up their mother");
        q3.setText("Say bad thing to him back untill you think you won");
        q4.setText("Ignore");
        
        if(q1.isSelected()){ 
            point = (point + 4);
            System.out.println(point);
        }
        else if(q2.isSelected()){
            point = (point + 3);
            System.out.println(point);
        }
        else if(q3.isSelected()){
         point = (point + 2);
         System.out.println(point);
        }
        else if(q4.isSelected()){
         point = (point + 1);
         System.out.println(point);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        b3.setVisible(false);
        b4.setVisible(true);
        
        WUR.setText("If you are winning what would you do");
        q1.setText("Tell the enime they are trash and get them triggered");
        q2.setText("Flex on everyone and tell them tell are bad");
        q3.setText("Start doing stubit things and wins");
        q4.setText("Acctually carry...Nah feeds");
        
        if(q1.isSelected()){ 
            point = (point + 4);
            System.out.println(point);
        }
        else if(q2.isSelected()){
            point = (point + 3);
            System.out.println(point);
        }
        else if(q3.isSelected()){
         point = (point + 2);
         System.out.println(point);
        }
        else if(q4.isSelected()){
         point = (point + 1);
         System.out.println(point);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        b4.setVisible(false);
        b5.setVisible(true);
        
        WUR.setText("What would you do if you are doing the best, but you group thinks the opposite");
        q1.setText("Start not trying and show them what they want");
        q2.setText("Leave the team");
        q3.setText("Tell them that they are the reason");
        q4.setText("Try to prove them wrong");
        
        if(q1.isSelected()){ 
            point = (point + 4);
            System.out.println(point);
        }
        else if(q2.isSelected()){
            point = (point + 3);
            System.out.println(point);
        }
        else if(q3.isSelected()){
         point = (point + 2);
         System.out.println(point);
        }
        else if(q4.isSelected()){
         point = (point + 1);
         System.out.println(point);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        b5.setVisible(false);
        b6.setVisible(true);
        
        WUR.setText("What would you do if someone isn't doing their job");
        q1.setText("Tell them to quit the posistion");
        q2.setText("Flame him till he cries");
        q3.setText("Tell them what to do");
        q4.setText("Say go practice ");
        
        if(q1.isSelected()){ 
            point = (point + 4);
            System.out.println(point);
        }
        else if(q2.isSelected()){
            point = (point + 3);
            System.out.println(point);
        }
        else if(q3.isSelected()){
         point = (point + 2);
         System.out.println(point);
        }
        else if(q4.isSelected()){
         point = (point + 1);
         System.out.println(point);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        System.out.println(point);
        q1.setVisible(false);
        q2.setVisible(false);
        q3.setVisible(false);
        q4.setVisible(false);
        
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        WUR.setVisible(false);
        
        if (point == (20)){
            this.setVisible(false);
            new Yasuo().setVisible(true);
        }
        else if (point >= (17)){
            this.setVisible(false);
            new Zoe().setVisible(true);
        }
        else if (point >= (13)){
            this.setVisible(false);
            new Riven().setVisible(true);
        }
        else if (point  >= (9)){
            this.setVisible(false);
            new Zed().setVisible(true);
        }
        else if (point >= (5)){
            this.setVisible(false);
            new Vayne().setVisible(true);
        }
        else if (point < (4)){
            WUR.setVisible(true);
            WUR.setText("Sorry, you might of missed a question");
        }
        //WUR.setText(point + "");
    }//GEN-LAST:event_b6ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        b.setVisible(false);
        b2.setVisible(true);
        //ask user the questions
        WUR.setText("What would You do if you are losing a game");
        q1.setText("Blame it on someone else");
        q2.setText("Start being toxic");
        q3.setText("Think you are still winning, and is super good");
        q4.setText("Keep losing");
        
        //score keep
        if(q1.isSelected()){ 
            point = (point + 4);
            System.out.println(point);
        }
        else if(q2.isSelected()){
            point = (point + 3);
            System.out.println(point);
        }
        else if(q3.isSelected()){
         point = (point + 2);
         System.out.println(point);
        }
        else if(q4.isSelected()){
         point = (point + 1);
         System.out.println(point);
        }
    }//GEN-LAST:event_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOLTQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOLTQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOLTQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOLTQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOLTQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WUR;
    private javax.swing.JButton b;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pic1;
    private javax.swing.JRadioButton q1;
    private javax.swing.JRadioButton q2;
    private javax.swing.JRadioButton q3;
    private javax.swing.JRadioButton q4;
    // End of variables declaration//GEN-END:variables
}
